### ISSUE TITLE
Cannot query SOCO directly from S3 public bucket

### ISSUE THREAD

**Issue by czer1mj** [single-cell-data/TileDB-SingleCell#164] opened 2022-06-17 14:56 UTC
I continually get an error when trying to query a SOCO from a public S3 bucket. This does not occur when I use boto3 to download a local copy of the SOCO in the same script.

Syntax to query S3 SOCO: 
`soco = tiledbsc.SOMACollection("s3://czi.bruce-public/demosoco/", config=tiledb.Config({"py.init_buffer_bytes": 128 * 1024 ** 2, "vfs.s3.region": "us-east-1"}))`

Error:
```
(soma) D:\data\scanpy>python slicingTest.py
[2022-06-15 11:11:55.387] [Process: 11156] [error] [Global] [TileDB::Array] Error: Cannot open array; Array does not exist
Traceback (most recent call last):
  File "D:\data\scanpy\slicingTest.py", line 32, in <module>
    pericyte_cells = soco.attribute_filter(
  File "c:\users\czerw\documents\github\tiledb-singlecell\apis\python\src\tiledbsc\soma_collection.py", line 158, in attribute_filter
    if not soma.obs.has_attr_names(obs_attr_names):
  File "c:\users\czerw\documents\github\tiledb-singlecell\apis\python\src\tiledbsc\tiledb_array.py", line 106, in has_attr_names
    attr_names_set = set(self.attr_names())
  File "c:\users\czerw\documents\github\tiledb-singlecell\apis\python\src\tiledbsc\tiledb_array.py", line 83, in attr_names
    with self._open() as A:
  File "c:\users\czerw\documents\github\tiledb-singlecell\apis\python\src\tiledbsc\tiledb_array.py", line 47, in _open
    return tiledb.open(self.uri, mode=mode, ctx=self._ctx)
  File "C:\Users\czerw\miniconda3\envs\soma\lib\site-packages\tiledb\highlevel.py", line 23, in open
    return tiledb.Array.load_typed(
  File "tiledb\libtiledb.pyx", line 3506, in tiledb.libtiledb.Array.load_typed
  File "tiledb\libtiledb.pyx", line 3332, in tiledb.libtiledb.preload_array
  File "tiledb\libtiledb.pyx", line 532, in tiledb.libtiledb._raise_ctx_err
  File "tiledb\libtiledb.pyx", line 517, in tiledb.libtiledb._raise_tiledb_error
tiledb.cc.TileDBError: [TileDB::Array] Error: Cannot open array; Array does not exist
```

This is using Windows 10 with AWS region config set to us-west-2

**Comment by bkmartinjr** [comment] 2022-06-17 15:18
it works fine from EC2/Linux and my Linux laptop (to the same object).  Perhaps a windows-specific issue?

**Comment by johnkerl** [comment] 2022-07-05 15:02
@czer1mj I cannot reproduce on Mac; I've been doing quite a bit of CLI/notebook work using public S3 buckets.

**Comment by johnkerl** [comment] 2022-08-01 05:08
@czer1mj closing this out -- please let me know if we need to re-open -- thank you! :)

**Closed by johnkerl** 2022-08-01 05:08 UTC
Labels: pending-feedback-to-close
